project:
  type: book
  output-dir: _book
  pre-render: print_quarto_config.py

book:
  title: "Tools for data science"
  author: "Thomas Gardos and Scott Ladenheim"
  date: "6/26/2024"
  chapters:
    - index.qmd
    - part: "Preliminaires"
      chapters:
        - 01-Intro-to-Python.qmd
        - 02A-Git.qmd
        - 02B-Pandas.qmd
        - 02C-Sklearn.qmd
        - 04-Linear-Algebra-Refresher.qmd
        - 03-Probability-and-Statistics-Refresher.qmd
        - 05-Distances-Timeseries.qmd
        - 05A-Learning.qmd
    - part: "Clustering"
      chapters:
        - 06-Clustering-I-kmeans.qmd
        - 07-Clustering-II-in-practice.qmd
        - 08-Clustering-III-hierarchical.qmd
        - 09-Clustering-IV-GMM-EM.qmd
    - part: "Classification"
      chapters:
        - 13-Learning-From-Data.qmd
        - 14-Classification-I-Decision-Trees.qmd
        - 15-Classification-II-kNN.qmd
        - 16-Classification-III-NB-SVM.qmd
    - part: "Dimensionality Reduction"
      chapters:
        - 10-Low-Rank-and-SVD.qmd
        - 11-Dimensionality-Reduction-SVD-II.qmd
      # - 12-Anomaly-Detection-SVD-III.qmd
    - part: "Regression"
      chapters:
        - 17-Regression-I-Linear.qmd
        - 18-Regression-II-Logistic.qmd
        - 19-Regression-III-More-Linear.qmd
    - part: "Neural Networks"
      chapters:
        - 23-NN-I-Gradient-Descent.qmd
        - 24-NN-II-Backprop.qmd
        - 25-NN-III-CNNs.qmd
    - part: "Selected Topics"
      chapters:
      # For now commenting out 20 because of reliance on 1.2GB train.csv
      #  - 20-Recommender-Systems.qmd
        - 21-Networks-I.qmd
        - 22-Networks-II-Centrality-Clustering.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
