name: Quarto Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-deploy"
  build-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # Downloads and installs the OS specific version of Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Check Quarto version
        shell: sh
        run: |
          echo "Checking Quarto version"
          quarto --version
          
      - name: Setup GraphViz CLI
        uses: ts-graphviz/setup-graphviz@v2

      - name: Check GraphViz dot version
        shell: sh
        run: |
          echo "Checking dot version"
          dot -V
          
      - name: Install Python and Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - run: pip install jupyter
      - run: pip install -r requirements.txt

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: ./ds701_book
        env:
          QUARTO_DENO_V8_OPTIONS: --stack-size=8192

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_book
        
#      - name: Render and Publish
#        uses: quarto-dev/quarto-actions/publish@v2
#        with:
#          path: ./ds701_book
#          target: gh-pages
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
